function [h_fig] = legend

h_fig = figure(...
'PaperPosition',get(0,'defaultfigurePaperPosition'),...
'Position',[100 100 550 500],... %adjust fit to screen
'Resize','off',...
'Tag','figure1');
set(h_fig,'MenuBar','none');

r = [1 0 0 1  1 0  1  1  0];
g = [0 1 0 1 .2 1 .5 .2 .4];
b = [0 0 1 0  1 1  0 .5  0];
titles = {'1/4 rest','dot','1/2 rest','whole rest','sharp','flat','natural','whole note','1/8 rest'};

% row 1
h1 = axes(...
'Parent',h_fig,...
'Units','pixels',...
'Position',[50 500-130 150 100],...
'XColor',get(0,'defaultaxesXColor'),...
'XTick',[],...
'XTickMode','manual',...
'YColor',get(0,'defaultaxesYColor'),...
'YTick',[],...
'YTickMode','manual');
imagesc(cat(3,r(1),g(1),b(1))); axis(h1,'off'); title(titles{1});

h2 = axes(...
'Parent',h_fig,...
'Units','pixels',...
'Position',[200 500-130 150 100],...
'XColor',get(0,'defaultaxesXColor'),...
'XTick',[],...
'XTickMode','manual',...
'YColor',get(0,'defaultaxesYColor'),...
'YTick',[],...
'YTickMode','manual');
imagesc(cat(3,r(2),g(2),b(2))); axis(h2,'off'); title(titles{2});

h3 = axes(...
'Parent',h_fig,...
'Units','pixels',...
'Position',[350 500-130 150 100],...
'XColor',get(0,'defaultaxesXColor'),...
'XTick',[],...
'XTickMode','manual',...
'YColor',get(0,'defaultaxesYColor'),...
'YTick',[],...
'YTickMode','manual');
imagesc(cat(3,r(3),g(3),b(3))); axis(h3,'off'); title(titles{3});


% row 2
h4 = axes(...
'Parent',h_fig,...
'Units','pixels',...
'Position',[50 500-260 150 100],...
'XColor',get(0,'defaultaxesXColor'),...
'XTick',[],...
'XTickMode','manual',...
'YColor',get(0,'defaultaxesYColor'),...
'YTick',[],...
'YTickMode','manual');
imagesc(cat(3,r(4),g(4),b(4))); axis(h4,'off'); title(titles{4});

h5 = axes(...
'Parent',h_fig,...
'Units','pixels',...
'Position',[200 500-260 150 100],...
'XColor',get(0,'defaultaxesXColor'),...
'XTick',[],...
'XTickMode','manual',...
'YColor',get(0,'defaultaxesYColor'),...
'YTick',[],...
'YTickMode','manual');
imagesc(cat(3,r(5),g(5),b(5))); axis(h5,'off'); title(titles{5});

h6 = axes(...
'Parent',h_fig,...
'Units','pixels',...
'Position',[350 500-260 150 100],...
'XColor',get(0,'defaultaxesXColor'),...
'XTick',[],...
'XTickMode','manual',...
'YColor',get(0,'defaultaxesYColor'),...
'YTick',[],...
'YTickMode','manual');
imagesc(cat(3,r(6),g(6),b(6))); axis(h6,'off'); title(titles{6});


% row 3
h7 = axes(...
'Parent',h_fig,...
'Units','pixels',...
'Position',[50 500-390 150 100],...
'XColor',get(0,'defaultaxesXColor'),...
'XTick',[],...
'XTickMode','manual',...
'YColor',get(0,'defaultaxesYColor'),...
'YTick',[],...
'YTickMode','manual');
imagesc(cat(3,r(7),g(7),b(7))); axis(h7,'off'); title(titles{7});

h8 = axes(...
'Parent',h_fig,...
'Units','pixels',...
'Position',[200 500-390 150 100],...
'XColor',get(0,'defaultaxesXColor'),...
'XTick',[],...
'XTickMode','manual',...
'YColor',get(0,'defaultaxesYColor'),...
'YTick',[],...
'YTickMode','manual');
imagesc(cat(3,r(8),g(8),b(8))); axis(h8,'off'); title(titles{8});

h9 = axes(...
'Parent',h_fig,...
'Units','pixels',...
'Position',[350 500-390 150 100],...
'XColor',get(0,'defaultaxesXColor'),...
'XTick',[],...
'XTickMode','manual',...
'YColor',get(0,'defaultaxesYColor'),...
'YTick',[],...
'YTickMode','manual');
imagesc(cat(3,r(9),g(9),b(9))); axis(h9,'off'); title(titles{9});



%trash
h10 = axes(...
'Parent',h_fig,...
'Units','pixels',...
'Position',[50 500-470 450 50],...
'XColor',get(0,'defaultaxesXColor'),...
'XTick',[],...
'XTickMode','manual',...
'YColor',get(0,'defaultaxesYColor'),...
'YTick',[],...
'YTickMode','manual');
imagesc(cat(3,.5,.5,.5)); axis(h10,'off'); title('trash');