# TCL File Generated by Component Editor 10.1sp1
# Tue Mar 29 21:24:26 EDT 2011
# DO NOT MODIFY


# +-----------------------------------
# | 
# | wait_for_interrupt_custom_instruction_0_91 "wait_for_interrupt_cust_inst0_91" v0.91
# | Brad Campbell 2011.03.29.21:24:26
# | 
# | 
# | C:/discotective/hardware/epac/wait_for_interrupt_custom_instruction.v
# | 
# |    ./wait_for_interrupt_custom_instruction.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 10.1
# | 
package require -exact sopc 10.1
# | 
# +-----------------------------------

# +-----------------------------------
# | module wait_for_interrupt_custom_instruction_0_91
# | 
set_module_property NAME wait_for_interrupt_custom_instruction_0_91
set_module_property VERSION 0.91
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Brad Campbell"
set_module_property DISPLAY_NAME wait_for_interrupt_cust_inst0_91
set_module_property TOP_LEVEL_HDL_FILE wait_for_interrupt_custom_instruction.v
set_module_property TOP_LEVEL_HDL_MODULE wait_for_interrupt_custom_instruction
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file wait_for_interrupt_custom_instruction.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point nios_custom_instruction_slave_0
# | 
add_interface nios_custom_instruction_slave_0 nios_custom_instruction end
set_interface_property nios_custom_instruction_slave_0 clockCycle 0
set_interface_property nios_custom_instruction_slave_0 operands 0

set_interface_property nios_custom_instruction_slave_0 ENABLED true

add_interface_port nios_custom_instruction_slave_0 reset reset Input 1
add_interface_port nios_custom_instruction_slave_0 start start Input 1
add_interface_port nios_custom_instruction_slave_0 done done Output 1
add_interface_port nios_custom_instruction_slave_0 result result Output 32
add_interface_port nios_custom_instruction_slave_0 clk clk Input 1
add_interface_port nios_custom_instruction_slave_0 clk_en clk_en Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point interrupt_in
# | 
add_interface interrupt_in conduit end

set_interface_property interrupt_in ENABLED true

add_interface_port interrupt_in interrupt export Input 1
# | 
# +-----------------------------------
